### ISSUE TITLE
Any handles command is throwng java.lang.Illegalstateexception

### ISSUE THREAD

**Issue by Magicmaan** [LotuxPunk/Handles#24]
![image](https://user-images.githubusercontent.com/38400400/75616089-8a097200-5b44-11ea-8ca2-c2833bfd9b0b.png)

On a server 
updated to cc:tweaked and now no handles command is working but is just throwing error.
See image to get full error

**Comment by LotuxPunk** [comment]
Could you break and replace the computer and TARDIS link then retry

**Comment by Magicmaan** [comment]
just did, still not working at all. some commands do seem to function though like startflight,getdestination,setdestination

**Comment by Magicmaan** [comment]
https://forums.spongepowered.org/t/causestackmanager-called-from-off-main-thread/20934
https://github.com/trentech/ProjectPortals/issues/87

Alright, i've been looking at it for a couple days and i think spongeforge is the problem, two links describe the exact same error. however, i know nothing of java to fix it

**Comment by LotuxPunk** [comment]
After some testing, I think the bug isn't on my side. It's probably CC:Tweaked who use thread at some point and SpongeForge seems afraid of that.
