### ISSUE TITLE
The new update

### ISSUE THREAD

**Issue by Josh65-2201** [LotuxPunk/Handles#27]
When doing m.getFuel() it says "attempt to call nil".
Also not sure if your doing this but the wiki needs to be updated with the new commands and where to get component IDs from.

**Comment by LotuxPunk** [comment]
The wiki isn't up to date yet. getFuelLevel isn't available anymore

**Comment by Josh65-2201** [comment]
is it possible to get the fuel level at all

**Comment by Josh65-2201** [comment]
Never mind found it thought the code
