### ISSUE TITLE
Mod has hard dependency on CC.

### ISSUE THREAD

**Issue by brisingraerowing** [LotuxPunk/Handles#3]
[Crash Log](https://gist.github.com/BrisingrAerowing/0c73b2298dacd09562a08845bd7e27f1)

**Comment by LotuxPunk** [comment]
Thanks ! I was pretty sure this bug was fixed, but apparently not. 👍

**Comment by LotuxPunk** [comment]
https://minecraft.curseforge.com/projects/handles/files/2657787
