### ISSUE TITLE
Setting desternation not working

### ISSUE THREAD

**Issue by Josh65-2201** [LotuxPunk/Handles#31]
when i do m.setTardisDestination(-2,45,2,0) it does not set the destination.

**Comment by LotuxPunk** [comment]
Which version do you use ? 1.14 ?

If yes, you just have to set the destination with x, y, z, the dimension is in another function.

**Comment by Jeryn99** [comment]
Yeah, I think what you're after is:

m.setDestination(-2,45,2);
m.setDimension(0);

**Comment by Josh65-2201** [comment]
i'm on 1.12.2
Edit: Turns out I didn't have the subsystem installed.
