### ISSUE TITLE
More control over Tardis with Handles

### ISSUE THREAD

**Issue by brianSites** [LotuxPunk/Handles#32]
I would like the ability to get more information about the Tardis and control the Tardis in even more ways with Handles. Here are a few things I'd like to see:

## Door Controls

Why should you let Handles take control of your doors? Well, for one, you won't need a key. All you need is a bit of computer knowledge, a pocket computer and your Tardis will be more secure than ever before. Forgot to lock your doors while being hundreds of blocks away? Just whip out the pocket computer and the doors will lock for you, keeping any captives in and any thieves out. Lost your key? Enter your passcode and the Tardis will unlock only for you and anyone you trust with the passcode. Don't want to let someone that knows the passcode in? Change it at a moment's notice and your beloved Tardis will be safe from any potential intruders.

## Fuel Observation

Artron fuel is very precious. Without it, your Tardis will fall out of the time vortex or not take off at all which is why it's important to keep a close eye on your Artron fuel level. Or better yet, let a computer do it. With this feature, you can set up a computer and, using a loop that triggers when you enter your Tardis, allow your Tardis will automatically refuel once it dips below a certain threshold. You also can ensure your Tardis automatically turns off the refueling protocols when it hits it's maximum. Or if you're running towards your Tardis and don't remember what fuel level your Tardis is at, you can have it look at its own fuel level and judge whether it needs to be filled up while you are coming so when you get there, it will be all fueled up for your next great adventure.

## Directional Facing

Currently, the Handles mod can allow your Tardis fly cross dimensions and anywhere within your fuel constraints while you sit back and watch the action unfold with only a pocket computer. However, it can not control which way your Tardis faces after it lands. This is not an important issue but if you are controlling your Tardis to pick you up or drop you off, it'll be in your best interest to ensure the entrance or exit to your Tardis is not hanging off a cliffside, overlooking the void or sitting on the edge of a lava pool. If you made a platform for your Tardis, this control is invaluable as you would want to exit the right direction and not fall 50 blocks to your grave or suffocate in solid stone.

## Life Signs

While you are roaming about, your Tardis is in a venerable state. Any players with a key or decent knowledge of your Tardis security system can break-in. Or maybe you just forgot to lock the front door. Either way, with this feature, we can make it send a message to your pocket computer, informing you of anyone or anything that classifies as a living thing in your Tardis. After you leave the Tardis, you can arm the system and when the life signs exceed your normal amount, it will alert you of unauthorized presence. Or you could just lock them in until your arrival.

## Alarm System Control

If there is a dangerous entity within your Tardis, it might be wise to let them know of your presence as to scare them off. But you certainly don't have time to check every room of your infinitely big Tardis. This feature ties in with the feature above. If it detects any anomalies using a life scan, you can set it to turn on the alarms, alerting you of an enemy presence or scaring off intruders. You can also just use it for jokes and frighten your friends.

## Flight Progress

Sometimes, you just want to sit back and leave your Tardis on autopilot. Or maybe you just want to know if your Tardis has arrived at your friend's house yet. Either way, I suggest two new functions be added, tardis.inFlight and tardis.getFlightProgress. tardis.inFlight() will return a boolean that represents whether your timeship is currently grounded or falling through the vortex. tardis.getFlightProgress will return a number between 1 and 99, signifying the ship's current progress through the vortex. These can be used for a variety of things like being alerted if someone else flys your Tardis or make pistons reveal blocks of ice when flying.

## [ Rejected ] Monitor Projection

A well-known feature of the Tardis mod is its ability to project the exterior of the Tardis to the Tardis monitor. In CC: Tweaked, there is also a monitor that can be joined to make a larger screen. You might understand where I am going with this. My suggestion is the ability to project the Tardis's exterior camera onto a pocket computer screen or a monitor so you can see the outside of your Tardis at all times.

**Comment by LotuxPunk** [comment]
> A well-known feature of the Tardis mod is its ability to project the exterior of the Tardis to the Tardis monitor. In CC: Tweaked, there is also a monitor that can be joined to be a large screen. You might understand where I am going with this. My suggestion is the ability to project the Tardis's exterior camera onto a pocket computer screen or a monitor so you can see the outside of your Tardis at all times.

I'm not really sure about this part, but the rest seems great !

**Comment by brianSites** [comment]
Okay, I guess that would be hard to code but I am glad you like all the other ideas. After you are done implementing all these ideas, can you consider adding autocomplete support?

**Comment by LotuxPunk** [comment]
> 
> 
> Okay, I guess that would be hard to code but I am glad you like all the other ideas. After you are done implementing all these ideas, can you consider adding autocomplete support?

Auto-complete support isn't on my side, it's CC:Tweaked messing with some stuff sometimes.
You have the auto-complete in LUA mode, but not at certain point in editing mode

**Comment by brianSites** [comment]
I edited the issue to include more things.

**Comment by brianSites** [comment]
Forgive me if I am just dumb but I think tardis.getDimensions is broken. If you loop through all the values, all of them are nil. If I print it out using print(), it will say "0 - minecraft:the_nether". This is good. But there is no way to get the other dimensional ids.

**Comment by LotuxPunk** [comment]
> Forgive me if I am just dumb but I think tardis.getDimensions is broken. If you loop through all the values, all of them are nil. If I print it out using print(), it will say "0 - minecraft:the_nether". This is good. But there is no way to get the other dimensional ids.

Please do another issue for this with screen shot and code pls
