### ISSUE TITLE
[ Suggestion ] Tardis Interfaces Can Be Implanted Inside Pocket Computers

### ISSUE THREAD

**Issue by brianSites** [LotuxPunk/Handles#33]
I propose pocket computers can be integrated with a Tardis Interface so pocket computers can also communicate with the Tardis without having to remotely contact an already existing computer. They would work as if you put a modem on the back of a pocket computer. To connect with the interface, you would use peripheral.wrap("back") like you would with wireless pocket computers. To craft a Tardis pocket computer, you would put a Tardis interface with a pocket computer inside a crafting bench.

**Comment by LotuxPunk** [comment]
Isn't going to happen, even if the idea is good, I need the block to be placed in the tardis to take controle of the TARDIS. I have no other way to technicaly do that.
