### ISSUE TITLE
tardis.getDimensions() returns nil

### ISSUE THREAD

**Issue by brianSites** [LotuxPunk/Handles#34]
```
local tardis = peripheral.wrap("top")
local dimensionsList = tardis.getDimensions()
for i = 0, #dimensionsList do
    print(dimensionsList[i])
end
```

The code above should print out every dimension and list them out. Instead, it returns 24 nil statements. There are a few problems with this, the first being that when I do #dimensionsList, it returns _24 dimensions_. I most certainly don't have that many dimensions. The second problem is that is I print out my list of dimensions, it returns the id for the nether. However, there is no way to get the code for any other dimensions.

**Comment by Magicmaan** [comment]
getdimensions() is a list, as such it needs to be placed inside a table, right now it is just pulling the first dimension and then since there is no further position does nil
"local dimensionsList = {tardis.getDimensions()}"
i think that should work
