### ISSUE TITLE
tardis.SetFlight(1) spams flight every tick

### ISSUE THREAD

**Issue by CMYKarma** [LotuxPunk/Handles#39]
If you use tardis.SetFlight(1) in the lua terminal it will start flight every tick.

If you remove the demat circuit it will keep trying and even if you remove the computer the spamming doesn't stop.

**Comment by LotuxPunk** [comment]
Thanks for the report ! Which version of Handles do you use ?

**Comment by CMYKarma** [comment]
1.16.5-1.0.0

https://www.youtube.com/watch?v=KpQiMcI53F0
