### ISSUE TITLE
Surprise, bug report!!

### ISSUE THREAD

**Issue by MishaPlayer** [LotuxPunk/Handles#4]
So basically here's the fucking reproduction steps because there's no physical way for you to know this otherwise.

Step one: TARDIS Mod V0.0.9A, get the aprioritron or whatever it's called.
Step two: Put it in the TARDIS. I'm not telling you how to do this.
Step three: Take it out. The menu changed.
Step four: Observe as it crashes, as the mod expects a description for the warning (eg. no demat circuit = no flight other bla bla bla shit)

If you _need_ a crashlog _that_ fucking badly, here you go.
[crash-2019-02-08_23.02.25-client.txt](https://github.com/LotuxPunk/Handles/files/2847488/crash-2019-02-08_23.02.25-client.txt)

EDIT: A kind reminder to the makers of the [main mod](https://github.com/Spectre0987/TardisMod/issues/180) because Stout Shako, give me two refined.

**Comment by Suffril** [comment]
You should be a lot politier when reporting issues, keep up this behaviour and your interaction privileges will be revoked from the other repos.
