### ISSUE TITLE
Vortex Limbo can't land

### ISSUE THREAD

**Issue by superjaja05** [LotuxPunk/Handles#46]
Heya, so i noticed that when the tardis is in Vortex Limbo mode, it seems i can't use Handles to make it land:
`setFlight(0)` doesn't do anything, `setSpeed(0)` moves the throttle lever but doesn't do anything
and same for `setHandbrake(true)` ; it only moves the handbrake but doesn't make the tardis land
I'm not sure if this is an issue on NTM's side or Handles side, but i thought i'd make an issue for that, in case its fixeable.

**Comment by superjaja05** [comment]
Oh wait, even in stabilized flight i apparently can't land the tardis either, so i suppose its more a feature request than a bug? not sure, but still it would be good if `setSpeed(0)` or `setFlight(0)` could land the tardis

**Comment by LotuxPunk** [comment]
Fixed in #48
