### ISSUE TITLE
setting flight to 0 doesnt do anything

### ISSUE THREAD

**Issue by ghost** [LotuxPunk/Handles#51]
doing tardis.setFlight(0) should land the tardis instead of nothing

i am going to assume handles performs actions on a players behalf like clicking the console
this mod can shift click blocks/buttons and other things
https://www.curseforge.com/minecraft/mc-mods/click-machine/files
 you might find how to shift click within the code or just by asking
and possibly be able to land a tardis using it

**Comment by LotuxPunk** [comment]
Hey !
Question : does the TARDIS while flying land if the speed is set to 0 manually by the player ? (With the handbrake free obviously)

**Comment by LotuxPunk** [comment]
And for your record, the mod work by some hacks directly on the tileentity of the console, so there's no "fake player" interaction involved in the process.

**Comment by leafreynolds** [comment]
> Hey ! Question : does the TARDIS while flying land if the speed is set to 0 manually by the player ? (With the handbrake free obviously)

If you mean manually, without a computer, yes you can. Using your hand, you can set throttle speed to zero, which always lands the Tardis without crashing it

**Comment by LotuxPunk** [comment]
> > Hey ! Question : does the TARDIS while flying land if the speed is set to 0 manually by the player ? (With the handbrake free obviously)
> 
> 
> 
> If you mean manually, without a computer, yes you can. Using your hand, you can set throttle speed to zero, which always lands the Tardis without crashing it

Hm. Will check it tomorrow. I don't understand why it'd not land with the code then.

There's probably some checks that happens during on the player interaction on the control (like the Handbrake)

Thanks for the info !

**Comment by LotuxPunk** [comment]
This commit should fix this, I don't have to time ti play test it for now. I'll asap. :)

Thanks for the report!
