### ISSUE TITLE
tardisinterface.setDoors(boolean) doesnt affect exterior door

### ISSUE THREAD

**Issue by BadDevilGrind** [LotuxPunk/Handles#6]
I am unsure if this should be reported here on on the New TARDIS Mod, but if you call the setDoors() function, only the interior door is affected, but not the exterior one.

This was tested by running the command remotely from outside the TARDIS. I verified that the message is coming through, since the remote command works from inside the TARDIS, where i can see that the interior door closes/opens, but while outside the exterior door remains in whatever state it was before the function was called.

**Comment by LotuxPunk** [comment]
Hey ! Thanks for the reporting, something probably change in the TARDIS Mod since the 0.1.0.C

I'll check that tonight or tomorrow, but an update is going to be release this Saturday normaly
